version: "3.8"
services:
  database:
    image: postgres
    container_name: ${PROJECT_NAME}-database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ${PROJECT_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  php-apache:
    container_name: ${PROJECT_NAME}-php-apache
    build:
      args:
        - PROJECT_NAME=${PROJECT_NAME}
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/${PROJECT_NAME}
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database

